name: Build and Push chromadb-instance to ECR

on:
  push:
    branches: [main]
    paths:
      - infra/chromedb-instance/**
      - apps/chromedb-instance/**

jobs:
  deploy:
    name: Build & Push Docker image to ECR
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-2
      ECR_REPO: chromadb-instance
      IMAGE_TAG: latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker buildx build \
          --platform linux/amd64 \
          -t $ECR_REPO:$IMAGE_TAG \
          -f app/chromedb-instance/Dockerfile .

    - name: Tag and Push to ECR
      run: |
        IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/$ECR_REPO:$IMAGE_TAG
        docker tag $ECR_REPO:$IMAGE_TAG $IMAGE_URI
        docker push $IMAGE_URI
