name: Build & Push chromadb-instance to Amazon ECR

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - infra/chromedb-instance/**
      - apps/chromedb-instance/**
  pull_request:
    branches: [main]
    paths:
      - infra/chromedb-instance/**
      - apps/chromedb-instance/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-southeast-2
      ECR_REPO_NAME: chromadb-instance
      IMAGE_TAG: latest

    steps:
    - name: 🔄 Checkout Code
      uses: actions/checkout@v3

    - name: 🔐 Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: 🔓 Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: 🛠️ Build Docker Image
      run: |
        docker buildx build \
          --platform linux/amd64 \
          -t $ECR_REPO_NAME:$IMAGE_TAG \
          -f apps/chromedb-instance/Dockerfile \
          apps/chromedb-instance

    - name: 📦 Tag & Push to ECR
      run: |
        IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:$IMAGE_TAG
        docker tag $ECR_REPO_NAME:$IMAGE_TAG $IMAGE_URI
        docker push $IMAGE_URI
